title: Émile Messelken
logo: "/images/img.jpg?raw=true" # your photo (or logo) here
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/emile-messelken/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal